name: BazaarPM5
version: 1.0.1
main: TheWindows\Bazaar\Main
api: [5.0.0]
author: TheWindows
depend:
  - EconomyAPI
  - FormAPI
permissions:
  winshop.command:
    description: Allows access to the bazaar command
    default: true
